### PR TITLE
Styling for Issue #2448185 by dsnopek: Support site logo by default

### PR DESCRIPTION
**Pull request by dsnopek**
See https://www.drupal.org/node/2448185

### CODE REVIEW

**Comment by arshad** [comment]
Thanks. Is https://www.drupal.org/node/2448185 RTBC?

**Comment by dsnopek** [comment]
No, it's still "Needs review", but it needs this PR in order to work correctly. This PR and the patch there need to be reviewed together.

**Comment by arshad** [comment]
Thanks. I'll test.

**Comment by arshad** [comment]
Looking good. Thanks.

**Comment by dsnopek** [comment]
Woohoo! Thanks :-)

**Pull request merged**
